### ISSUE TITLE
Explore how to represent `BV::ugt`, `BV::lt` as bitvector AST in Z3

### ISSUE THREAD

**Issue by ninehusky** [ninehusky/chompy-egglog#24]
Right now, there's a type mismatch when attempting to construct bitvector expressions which do `gt` or `lt`.

**Comment by ninehusky** [comment]
One starting point to this might be using `z3::ast::Dynamic` (see [here](https://docs.rs/z3/latest/z3/ast/struct.Dynamic.html)), and/or somehow converting booleans to bitvectors.

**Comment by ninehusky** [comment]
Or, [`z3::Bool::ite`](https://docs.rs/z3/latest/z3/ast/struct.Bool.html#method.ite)?

Greater than can expand to something like `(ite (gt a b) ONE ZERO)`.

**Comment by ekiwi** [comment]
> Greater than can expand to something like `(ite (gt a b) ONE ZERO)`.

If you want to treat your 1-bit bit vectors as bools, then what you are suggesting is the same approach that I have been using: https://github.com/cucapra/patronus/blob/ede6dae2f606acf75784b8354258359e18250626/src/smt/serialize.rs#L296

The inverse (if you would like to use a 1-bit bit vector as the condition to an ITE) would be:
https://github.com/cucapra/patronus/blob/ede6dae2f606acf75784b8354258359e18250626/src/smt/serialize.rs#L305

Hope this helps!

**Comment by ninehusky** [comment]
Sorry for the late response! Yep -- I ended up doing an approach very similar to what you promosed @ekiwi . Thanks for the suggestion! :)
